### ISSUE TITLE
`GeditDocument' does not have property `newline-type'

### ISSUE THREAD

**Issue by webmaster128** [editorconfig/editorconfig-gedit#15]
After installing version 0.5.3 of this plugin and the core lib EditorConfig-0.12.1-py3-none-any.whl from pip3, I the the following error when opening a document

```
Traceback (most recent call last):
  File "/home/me/.local/share/gedit/plugins/editorconfig_plugin/shared.py", line 40, in set_config
    self.set_end_of_line(document, props.get('end_of_line'))
  File "/home/me/.local/share/gedit/plugins/editorconfig_plugin/shared.py", line 81, in set_end_of_line
    document.set_property('newline-type', 0)
TypeError: object of type `GeditDocument' does not have property `newline-type'
```

Gedit 3.18.3 from Ubuntu 16.04.

**Comment by xuhdev** [comment]
It's a bit weird. Looks like `newline-type` is clearly defined as a property of `GeditDocument`: https://developer.gnome.org/gedit/3.0/gedit-gedit-document.html

**Comment by webmaster128** [comment]
I don't have a clue how gedit development is organized, but if this commit from June 2014 landed in the software, the property was removed: https://mail.gnome.org/archives/commits-list/2014-June/msg07239.html

The property was documented up to [3.12](https://developer.gnome.org/gedit/3.12/gedit-gedit-document.html) but is missing starting with [3.14](https://developer.gnome.org/gedit/3.14/gedit-gedit-document.html).

Do you know what *The property has been migrated to GtkSourceFile.* means? Can GtkSourceFile be used instead?

**Comment by TriMoon** [comment]
> @webmaster128 
Do you know what The property has been migrated to GtkSourceFile. means? Can GtkSourceFile be used instead?

It means it is **replaced** by `GtkSourceFile`, you need to check it's use if it is _"a drop-in compatible"_ property with the old one...

**Comment by ferdnyc** [comment]
I know this is a very old issue, but as I'm about to submit a PR to not-address this (meaning, silently ignore `end_of_line` due to the loss of `newline-type`), I thought I'd also share the findings that led me to that point.

Several properties of `GeditDocument`, including `newline-type`, were [deprecated in Gedit 3.14](https://wiki.gnome.org/Apps/Gedit/API-Changes) "Due to a new file loading and saving API in GtkSourceView".

The replacement for the `GeditDocument.newline-type` property, as noted, is `GtkSourceFile.newline-type`.

**`GtkSourceFile.newline-type` [is a read-only property](https://developer.gnome.org/gtksourceview/stable/GtkSourceFile.html).**

Gedit 3.14+ no longer provides any means of _setting_ the line-ending mode, only of querying it. There is, therefore, nothing editorconfig-gedit can do except to ignore `end_of_line`.

Hence PR #23, which I'm already applying to the `gedit-plugin-editorconfig` package in Fedora.
